[general]
import = [
	"catppuccin-macchiato.toml",
]

[window]
opacity = 0.8
blur = true

[font]
# normal = { family = "JetBrains Mono", style = "Regular" }
# normal = { family = "JetBrains Mono NL Nerd Font", style = "Regular" }
normal = { family = "MesloLGM Nerd Font", style = "Regular" }
size = 14.0

[cursor]
style = {shape = "Block", blinking = "Always"}
